name: Test Action
on: [ push ]
jobs:
  windows_test:
    runs-on: windows-latest
    name: Windows Test Job
    steps:
    - name: Windows Test Info
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        details: Test succeeded.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Warn
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: warn
        details: Test warning.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Error
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: error
        details: Test error.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Custom
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Success
      uses: dusmartijngames/discord-webhook-notify@master
      if: success()
      with:
        severity: info
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Failure
      uses: dusmartijngames/discord-webhook-notify@master
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Cancelled
      uses: dusmartijngames/discord-webhook-notify@master
      if: cancelled()
      with:
        severity: warn
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  linux_test:
    runs-on: ubuntu-latest
    name: Linux Test Job
    steps:
    - name: Linux Test Info
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        details: Test succeeded.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Warn
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: warn
        details: Test warning.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Error
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: error
        details: Test error.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Custom
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Success
      uses: dusmartijngames/discord-webhook-notify@master
      if: success()
      with:
        severity: info
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Failure
      uses: dusmartijngames/discord-webhook-notify@master
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Cancelled
      uses: dusmartijngames/discord-webhook-notify@master
      if: cancelled()
      with:
        severity: warn
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  macos_test:
    runs-on: macos-latest
    name: MacOS Test Job
    steps:
    - name: MacOS Test Info
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        details: Test succeeded.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Warn
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: warn
        details: Test warning.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Error
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: error
        details: Test error.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Custom
      uses: dusmartijngames/discord-webhook-notify@master
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Success
      uses: dusmartijngames/discord-webhook-notify@master
      if: success()
      with:
        severity: info
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Failure
      uses: dusmartijngames/discord-webhook-notify@master
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Cancelled
      uses: dusmartijngames/discord-webhook-notify@master
      if: cancelled()
      with:
        severity: warn
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
